### ISSUE TITLE
[launch files] Ambiguous filename

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/Poseidon#197]
What's the functional difference between hydrobox_replay.launch and hydrobox_all_play.launch ?

**Comment by Ddoiron-cidco** [comment]
hydrobox_replay.launch was used to replay diferent bag files 
 hydrobox_all_play.launch was user to replay the file with all the topics. 
 
 file are renamed to play_all.launch to start the aaa.all.gab
used to replay all the stream
 
 and play_gns_imu_sonar.launch to start zzz_gnss.bag zzz_imu-data.bag and zzz_sonar.bag
used to process the data by the system

**Comment by glabmoris** [comment]
Solved. Closing issue
