### ISSUE TITLE
Support for magnetic declination correction from a model 

### ISSUE THREAD

**Issue by PMNDI3** [CIDCO-dev/Poseidon#198]
True North used in geodesy can be calculated with NRCAN or NOAA applications. Here are the useful links:
https://geomag.nrcan.gc.ca/calc/mdcal-fr.php
https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml
TrueNorth=NorthMag-Declination

This fix is appropriate to avoid handling errors in datagrams when importing into caris for processing= problem currently encountered.

**Comment by glabmoris** [comment]
Handled in post-processing.

closing issue
