### ISSUE TITLE
imu bno055 calibration error

### ISSUE THREAD

**Issue by Ddoiron-cidco** [CIDCO-dev/Poseidon#202]
error with the calibration files 

the files is generate with bad chmod
![image](https://user-images.githubusercontent.com/58708562/101815556-b4ce2100-3aed-11eb-8594-def66588d095.png)

causing error on recalibration
![image](https://user-images.githubusercontent.com/58708562/101815497-9ff18d80-3aed-11eb-859b-b9ad91d2629a.png)

**Comment by glabmoris** [comment]
Fixed
