### ISSUE TITLE
[Hardware] MUX NMEA0183

### ISSUE THREAD

**Issue by Ddoiron-cidco** [CIDCO-dev/Poseidon#21]
voici une solution qui pourais regler notre probleme de latency.

https://www.yachtd.com/products/multiplexer.html

c'Est un multiplexeur pour du nmea 5 entré sortie nmea0183 et un port Seatalk

Cela permeterais d'avoir sur le port série matériel du raspberry 4 équipement nmea0183

**Comment by glabmoris** [comment]
Closed due to inactivity
