### ISSUE TITLE
Intégration Septentrio Mosaic X5 

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/Poseidon#223]
Selon le même pattern que le module Ublox F9P, lire les données binaires du module via USB et les logger dans un fichier binaire.

**Comment by JordanMcManus** [comment]
Mosaic-X5 sur le pickup:

![MosaicX5](https://user-images.githubusercontent.com/36419498/135527632-c80f17e1-f499-4189-afef-a0bf165bf34a.png)
