### ISSUE TITLE
Ajout d'un RTC

### ISSUE THREAD

**Issue by tomypineau** [CIDCO-dev/Poseidon#265]
Pour que le système puisse avoir une base de temps si le signal GPS n'est pas fonctionnel.

Nous avons déjà utilisé un DS3231MZ avec un pi qui fonctionnait bien.

**Comment by glabmoris** [comment]
C'est un ajout intéressant, il faudrait ajouter de la logique autour de chrony pour inclure la synchro de la RTC au temps satellite (via rtcsync) et l'inverse (RTC vers sysclock) lorsqu'on n'a pas de fix GPS/PPS et que l'horloge système n'est pas à l'heure (car si on fait juste perdre le fix GPS, l'horloge systeme continue de fonctionner, seulement avec des risques de drift).

**Comment by Ddoiron-cidco** [comment]
Test with GPS stream cut

before disconnecting the antenna
![image](https://user-images.githubusercontent.com/58708562/155382690-4827746f-a969-44c3-ba71-8d2dfcff7cd5.png)

during the antenna disconected
![image](https://user-images.githubusercontent.com/58708562/155382798-d2d7271b-8e94-45e4-b4e1-c79a9f6376c3.png)

when reconnecting the antenna
![image](https://user-images.githubusercontent.com/58708562/155383190-b49a97f8-b285-4767-af93-9aed1d4101c4.png)

the gps is in fix 3D
![image](https://user-images.githubusercontent.com/58708562/155383325-8d848525-2b59-47a6-ba00-9a0fe6d7156d.png)

after 1 min
![image](https://user-images.githubusercontent.com/58708562/155383462-59461511-94d4-452c-ab6b-da4f4773ec12.png)

after 5 min
![image](https://user-images.githubusercontent.com/58708562/155383562-66e97501-b7df-4e06-a489-6c3221a41239.png)

**Comment by glabmoris** [comment]
Done in #278
