### ISSUE TITLE
[Raspberry pi 4] Heat management

### ISSUE THREAD

**Issue by Ddoiron-cidco** [CIDCO-dev/Poseidon#296]
we should look to add a fan on the raspberry 

With a dicipator the temperature rice between 55 and 65C and the maximal is 80C 

We should add a fan like : 
https://www.waveshare.com/wiki/Fan_HAT
https://www.amazon.ca/-/fr/Waveshare-Ventilateur-Raspberry-temp%C3%A9rature-automatique/dp/B087PVD2GP/ref=sr_1_42?__mk_fr_CA=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=raspberry+fan&qid=1653662182&sr=8-42

**Comment by glabmoris** [comment]
Fixed
