### ISSUE TITLE
transfer of the binary file when stopping the recording

### ISSUE THREAD

**Issue by Ddoiron-cidco** [CIDCO-dev/Poseidon#304]
When wi stop the logging session on the web interface of poseidon the txt log are transfered in the /record directory and they are ready to get download

But for the gnss binary log we have to wait the 60 min log interval to download the files.

I suggest to write the files in a directory under /tmp like /tmp/Poseidon_log

in the txt log : When we stop the logging session *.txt are moved in the /record directory and *.* are copied (it will copy the partial gnss binairy file) 

the binairy logger will continue to populate the binairy file and will move the file when the 60 min will be compleet.

**Comment by glabmoris** [comment]
Fixed
