### ISSUE TITLE
[node_zed_f9p] memory hole

### ISSUE THREAD

**Issue by Ddoiron-cidco** [CIDCO-dev/Poseidon#312]
after few day the node take over 4Go of RAM.

**Comment by glabmoris** [comment]
The malloc() at line 366 doesn't have a free() in this file :

https://github.com/CIDCO-dev/Poseidon/blob/master/src/workspace/src/gnss_zed_f9p/include/gnss_zed_f9p/gnss_zed_f9p.h

**Comment by Ddoiron-cidco** [comment]
FIXED !!
