### ISSUE TITLE
[gnss_ZED-F9P] High CPU usage

### ISSUE THREAD

**Issue by Ddoiron-cidco** [CIDCO-dev/Poseidon#314]
If the serial port in the launch files is not present on the machine the node use 100% of the cpu

![image](https://user-images.githubusercontent.com/58708562/214335634-3f2977ac-4e34-438b-9cec-b347da665d26.png)

**Comment by glabmoris** [comment]
This is a hardware issue.

Closing under the assumption that software follows the hardware.
