### ISSUE TITLE
IMU calibration.dat

### ISSUE THREAD

**Issue by patcmorneau** [CIDCO-dev/Poseidon#327]
All the path in the launch files have been changed already.
for example in : `launch/Hydrobox/hydrobox_nmeadevice_ZED-F9P_bno055.launch`
we have :
```
<node ns="imu" name="imu_node" pkg="imu_bno055" type="bno055_i2c_node" respawn="true" respawn_delay="2" output="screen">
        <param name="device" type="string" value="/dev/i2c-1"/>
        <param name="address" type="int" value="40"/> <!-- 0x28 == 40 is the default for BNO055 -->
        <param name="frame_id" type="string" value="imu"/>
	<param name="calibrationFile" type="string" value="/opt/Poseidon/calibration.dat" />
```

but i still get the error message :
`[ERROR] [1679075054.482277046]: No calibration file found at /home/ubuntu/Poseidon/calibration.dat`

The error message is produced by: `bno055_i2c_activity.cpp` at line 120

in file `bno055_i2c_node.cpp`
we are passing the path `/home/ubuntu/Poseidon/calibration.dat` to the constructor

**Comment by glabmoris** [comment]
Fixed in #319
