### ISSUE TITLE
[web-interface] confinguration page

### ISSUE THREAD

**Issue by Ddoiron-cidco** [CIDCO-dev/Poseidon#331]
replace the dynamic page generation by static and with JS hide not used block

add block by type of content

sonar, csb connection .....

convert config.txt to json and validate json transmission on the web page
![image](https://user-images.githubusercontent.com/58708562/229138881-567d83da-b768-4784-9ff9-9d6aa0105a84.png)

should be
[
  "apiKey": "C6388A4F547EBB1BCF4EF140C9F0363EC3952A28607BD182377D4FED9FE9FF076CAEA9E21E5767ABC95EF907903E84389498F0BCEB662E073EFE3B1C89C4D473"
  ,
  "apiTarget": "/CSBWeb/JobServlet"
 ,.....

**Comment by glabmoris** [comment]
We have not reached a point where we have a fixed set of values to justify moving to static.
