### ISSUE TITLE
[Vitals / logger] 

### ISSUE THREAD

**Issue by Ddoiron-cidco** [CIDCO-dev/Poseidon#384]
Vitals node report hdd full when it is not the case 
![image](https://github.com/CIDCO-dev/Poseidon/assets/58708562/1a8a0792-4ba6-4843-a971-b909357c78f9)

![image](https://github.com/CIDCO-dev/Poseidon/assets/58708562/757d4815-48e6-45d1-8bbb-d2086770feef)

the dashboard indicate the error 
![image](https://github.com/CIDCO-dev/Poseidon/assets/58708562/29d758b0-e629-4c90-af40-318708bafa43)

but the system is still logging new data 

![image](https://github.com/CIDCO-dev/Poseidon/assets/58708562/1b4c35c1-bcc4-4206-81c7-41785bff5561)

**Comment by glabmoris** [comment]
Cannot reproduce
